YkProject/Yk.Web/ViewComponents/NavbarViewComponent.cs
using Yk.Data;
using Yk.Domain;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Yk.Web.ViewComponents
{
    [ViewComponent(Name = "Navbar")]
    public class NavbarViewComponent : ViewComponent
    {
        private readonly EfDbContext context;
 
        public NavbarViewComponent(EfDbContext context )
        {
         
            this.context = context;
        }
         
     
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var pages = await context.Set<Navmenu>().Where(i => !i.IsDeleted).OrderBy(x => x.MenuIndex).ToListAsync();

            return View(pages);
        }

    }
}

YkProject/Yk.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

@{
    Layout = null;


}


<!DOCTYPE html>
<html class="loading" lang="tr" data-textdirection="ltr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">


    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta name="description" content="Yk Project ">
    <meta name="keywords" content=""Yk Project">
    <meta name="author" content="Yk Project">

    <meta name="author" content="PIXINVENT">
    <title>
        @ViewData["Title"] | Yk Project
    </title>
    <link rel="apple-touch-icon" href="~/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Quicksand:300,400,500,700"
          rel="stylesheet">
    <link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css"
          rel="stylesheet">
    <!-- BEGIN VENDOR CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/vendors.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/extensions/sweetalert.css">

    @RenderSection("VendorCss", false)
    <!-- END VENDOR CSS-->
    <!-- BEGIN MODERN CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/app.css">
    @RenderSection("ModernCss", false)
    <!-- END MODERN CSS-->
    <!-- BEGIN Page Level CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/menu/menu-types/horizontal-menu.css">
    @RenderSection("LevelCss", false)
    <!-- END Page Level CSS-->
    <!-- BEGIN Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">
    <!-- END Custom CSS-->

</head>
<body class="horizontal-layout horizontal-menu horizontal-menu-padding 2-columns   menu-expanded" data-open="click" data-menu="horizontal-menu" data-col="2-columns">
    <nav class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow navbar-static-top navbar-light navbar-brand-center">
        <div class="navbar-wrapper " style="        padding: 10px;
        padding-left: 100px !important;
        padding-right: 100px !important;">

            <div class="navbar-container container center-layout">
                <div class="collapse navbar-collapse" id="navbar-mobile">
                    <ul class="nav navbar-nav mr-auto float-left font-size-large">

                        <li class="nav-item d-none d-md-block">
                            <a class="navbar-brand" href="/">
                                <img style="        height: 80% !important;
        width: 80% !important;" alt="Yk Project " src="~/Content/images/yklogo.jpg">
                            </a>
                        </li>

                         

                    </ul>
                    <ul class="nav navbar-nav float-right">
                        <li class="dropdown dropdown-user nav-item"> 


                        </li>



                    </ul>
                </div>
            </div>
        </div>
    </nav>

    @await Component.InvokeAsync("Navbar") 
    <div class="app-content container center-layout mt-2">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body"  >
                @RenderBody()
            </div>
        </div>
    </div> 

    <footer class="footer footer-transparent footer-light navbar-shadow">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2 container center-layout">
            <span class="float-md-left d-block d-md-inline-block">
                Copyright &copy; 2018 , Yk Project
            </span>
            <span class="float-md-right d-block d-md-inline-blockd-none d-lg-block">Yazılım Birimi <i class="ft-heart pink"></i></span>
        </p>
    </footer>
    <!-- BEGIN VENDOR JS-->
    <script src="~/app-assets/vendors/js/vendors.min.js" type="text/javascript"></script>

    <!-- BEGIN VENDOR JS-->
    <!-- BEGIN PAGE VENDOR JS-->
    <script type="text/javascript" src="~/app-assets/vendors/js/ui/jquery.sticky.js"></script>
    @RenderSection("VendorJs", false)
    <!-- END PAGE VENDOR JS-->
    <!-- BEGIN MODERN JS-->
    <script src="~/app-assets/js/core/app-menu.js" type="text/javascript"></script>
    <script src="~/app-assets/js/core/app.js" type="text/javascript"></script>
    <script src="~/app-assets/js/scripts/customizer.js" type="text/javascript"></script>
    @RenderSection("ModernJs", false)
    <!-- END MODERN JS-->
    <!-- BEGIN PAGE LEVEL JS-->
    @RenderSection("LevelJs", false)
    <script src="~/app-assets/vendors/js/extensions/sweetalert.min.js" type="text/javascript"></script>
    <!-- END PAGE LEVEL JS-->
    @RenderSection("Scripts", required: false)


</body>
</html>